### ISSUE TITLE
Strange Error with Raspberry Pi 4 Model B Rev 1.2

### ISSUE THREAD

**Issue by mmohrmmir** [rpi-ws281x/rpi-ws281x-java#17]
Hi 
I have a running Java Program on a  Raspberry Pi 4 Model B Rev 1.1.
Now I try to use the same SD Card in a  Raspberry Pi 4 Model B Rev 1.2 and got this error:

20:33:05.263 [main] INFO  com.github.mbelling.ws281x.Ws281xLedStrip - Native library loaded
Exception in thread "main" java.lang.RuntimeException: Failed to setup lights driver, result code: WS2811_ERROR_HW_NOT_SUPPORTED
	at com.github.mbelling.ws281x.Ws281xLedStrip.init(Ws281xLedStrip.java:234)
	at com.github.mbelling.ws281x.Ws281xLedStrip.<init>(Ws281xLedStrip.java:98)
	at WS28Test.main(WS28Test.java:4)

The "test" Program runs on both Pi's 
Any idea what is going wrong?
Regards 
Martin

**Comment by mmohrmmir** [comment]
Workaround: Delete the following line in createNativeLib.sh
git checkout 6851d9fb090f8a4703d2ceac97da2de617b09e8d
Regards
Martin

**Comment by Athanasie** [comment]
Hello,

Same problem here. Your workaround doesn't work for me.
Any other suggestions?

Christoph

**Comment by Gadgetoid** [comment]
This is a deliberate hard failure in the underlying `rpi_ws281x` C library to avoid running on hardware that hasn't been tested. It might be related to - https://github.com/jgarff/rpi_ws281x/issues/376

Revision IDs change depending on RAM amount, so I'm going to guess you're using an 8GB Pi 4 1.2?

**Comment by Athanasie** [comment]
Thanks for the fast answer.

No, I'm using the 4GB PI4 1.2 with newest stable Raspberry Pi OS.

**Comment by Athanasie** [comment]
Here the logfile from a fresh try:

`---------------  S U M M A R Y ------------

Command Line: WS28Test

Host: rev 3 (v7l), 4 cores, 1G, Raspbian GNU/Linux 10 (buster)
Time: Sun Aug  9 09:49:55 2020 CEST elapsed time: 3 seconds (0d 0h 0m 3s)`

Not sure, but I guess my raspi isn't recognized right. 

[hs_err_pid9601.log](https://github.com/rpi-ws281x/rpi-ws281x-java/files/5046870/hs_err_pid9601.log)

**Comment by Gadgetoid** [comment]
Looks like the issue with `createNativeLib.sh` is on the right track, since it's currently tracking a version before the Pi 4 Hardware Versions were added, as near as I can tell- https://github.com/jgarff/rpi_ws281x/compare/6851d9fb090f8a4703d2ceac97da2de617b09e8d..master

It's most likely you just need to make sure the library properly rebuilds against the latest version of the upstream code. Could try replacing the commit hash mentioned above with - 31f668cc637cd96e132b611db82cbe9de9838366

It's possible though unlikely that you have an unknown version of the Pi 4 that's not available upstream yet- you can find this by running: `grep Revision /proc/cpuinfo`

**Comment by Athanasie** [comment]
This hash worked, thank you.

**Comment by Gadgetoid** [comment]
Excellent - @mbelling is there any reason why the hash can't be bumped in the install script? I don't want to presume and break something.

**Comment by mbelling** [comment]
@Gadgetoid there is no reason this cannot be updated if it works with the new models.  I do not have a Pi4 to test with, but it sounds like it worked for @Athanasie.

If you want to submit a pull request I can merge it in.
